import Damian_Coloma.libreria_damian

assert (Damian_Coloma.libreria_damian.felicitacion("Mirella")=="Feliz cumpleaños Mirella")
assert (Damian_Coloma.libreria_damian.felicitacion("Sofia")=="Feliz cumpleaños Sofia")
assert (Damian_Coloma.libreria_damian.felicitacion("Ana")=="Feliz cumpleaños Ana")
assert (Damian_Coloma.libreria_damian.felicitacion("Diego")=="Feliz cumpleaños Diego")
assert (Damian_Coloma.libreria_damian.felicitacion("Fernando")=="Feliz cumpleaños Fernando")
print("FELICITACION OK")

assert(Damian_Coloma.libreria_damian.palabra_longitud("Mesa")==False)
assert(Damian_Coloma.libreria_damian.palabra_longitud("Sofia")==True)
assert(Damian_Coloma.libreria_damian.palabra_longitud("Rosado")==False)
assert(Damian_Coloma.libreria_damian.palabra_longitud("Verde")==True)
assert(Damian_Coloma.libreria_damian.palabra_longitud("Lapiz")==True)
print("PALABRA_LONGITUD OK")

assert(Damian_Coloma.libreria_damian.producto(12,11,3,5)==1980)
assert(Damian_Coloma.libreria_damian.producto(2,1,32,5)==320)
assert(Damian_Coloma.libreria_damian.producto(22,11,9,5)==10890)
assert(Damian_Coloma.libreria_damian.producto(34,11,8,7)==16830)
assert(Damian_Coloma.libreria_damian.producto(18,10,2,6)==2160)
print("PRODUCTO OK")

assert(Damian_Coloma.libreria_damian.validar_real(15.5)==True)
assert(Damian_Coloma.libreria_damian.validar_real(16)==False)
assert(Damian_Coloma.libreria_damian.validar_real(11.3)==True)
assert(Damian_Coloma.libreria_damian.validar_real(19)==False)
assert(Damian_Coloma.libreria_damian.validar_real(16.3)==True)
print("VALIDAR_REAL OK")

assert (Damian_Coloma.libreria_damian.nombre_longitud("Monica")== True)
assert (Damian_Coloma.libreria_damian.nombre_longitud("Andres")== True)
assert (Damian_Coloma.libreria_damian.nombre_longitud("Juan")== False)
assert (Damian_Coloma.libreria_damian.nombre_longitud("Alejandra")== False)
assert (Damian_Coloma.libreria_damian.nombre_longitud("Maria")== False)
print("NOMBRE OK")

assert(Damian_Coloma.libreria_damian.validar_palabra("Juana")== True)
assert(Damian_Coloma.libreria_damian.validar_palabra("Rojo")== True)
assert(Damian_Coloma.libreria_damian.validar_palabra("Perro")== True)
assert(Damian_Coloma.libreria_damian.validar_palabra("Benjamin")== True)
assert(Damian_Coloma.libreria_damian.validar_palabra("Ana")== True)
print("PALABRA OK")

assert(Damian_Coloma.libreria_damian.frase_longitud("Municipal")==True)
assert(Damian_Coloma.libreria_damian.frase_longitud("Ropero")==True)
assert(Damian_Coloma.libreria_damian.frase_longitud("Auxilio")== False)
assert(Damian_Coloma.libreria_damian.frase_longitud("HACECALOR")==True)
assert(Damian_Coloma.libreria_damian.frase_longitud("TENGOHAMBRE")==False)
print("FRASE OK")

assert(Damian_Coloma.libreria_damian.pedir_codigo("170770B")== True)
assert(Damian_Coloma.libreria_damian.pedir_codigo("75678")== False)
assert(Damian_Coloma.libreria_damian.pedir_codigo("73708778")== True)
assert(Damian_Coloma.libreria_damian.pedir_codigo("160988C")== True)
assert(Damian_Coloma.libreria_damian.pedir_codigo("123968B")== True)
print("CODIGO OK")

assert(Damian_Coloma.libreria_damian.pedir_dni("73708778")==True)
assert(Damian_Coloma.libreria_damian.pedir_dni("73767787")==True)
assert(Damian_Coloma.libreria_damian.pedir_dni("80644096")==True)
assert(Damian_Coloma.libreria_damian.pedir_dni("67875899")==True)
assert(Damian_Coloma.libreria_damian.pedir_dni("45678909")==True)
print("DNI OK")

assert(Damian_Coloma.libreria_damian.mensaje("Trabajo comunicacion"=="Excelente trabajo de comunicacion"))
assert(Damian_Coloma.libreria_damian.mensaje("Trabajo matematica"=="Excelente trabajo de matematica"))
assert(Damian_Coloma.libreria_damian.mensaje("Trabajo filosofia"=="Excelente trabajo de filosofia"))
assert(Damian_Coloma.libreria_damian.mensaje("Trabajo arte"=="Excelente trabajo de arte"))
assert(Damian_Coloma.libreria_damian.mensaje("Trabajo lenguaje"=="Excelente trabajo de lenguaje"))
print("TRABAJO OK")

assert(Damian_Coloma.libreria_damian.deuda_proemdio(2000,4000,5000)==3666)
assert(Damian_Coloma.libreria_damian.deuda_proemdio(1000,3000,7800)==3933.3)
assert(Damian_Coloma.libreria_damian.deuda_proemdio(15000,400,300)==5233.3)
assert(Damian_Coloma.libreria_damian.deuda_proemdio(2980,3400,200)==2193.3)
assert(Damian_Coloma.libreria_damian.deuda_proemdio(4560,8700,5000)==4586.6)
print("DEUDA OK")

assert(Damian_Coloma.libreria_damian.validar_cadena("Simba"==True))
assert(Damian_Coloma.libreria_damian.validar_cadena("Matematica"==True))
assert(Damian_Coloma.libreria_damian.validar_cadena("Rosado"==True))
assert(Damian_Coloma.libreria_damian.validar_cadena("Sacar"==True))
assert(Damian_Coloma.libreria_damian.validar_cadena("Verde"==True))
print("CADENA OOK")

assert(Damian_Coloma.libreria_damian.codigo_longitud("787087J")==True)
assert(Damian_Coloma.libreria_damian.codigo_longitud("78708A")== False)
assert(Damian_Coloma.libreria_damian.codigo_longitud("167659K")==True)
assert(Damian_Coloma.libreria_damian.codigo_longitud("181920A")==True)
assert(Damian_Coloma.libreria_damian.codigo_longitud("756")==False)
print("CODIGO OK")

assert(Damian_Coloma.libreria_damian.promedio(14,15,16,17,19)==16.2)
assert(Damian_Coloma.libreria_damian.promedio(4,5,16,13,20)==11.6)
assert(Damian_Coloma.libreria_damian.promedio(9,7,16,11,19)==12.4)
assert(Damian_Coloma.libreria_damian.promedio(11,13,16,18,19)==15.4)
assert(Damian_Coloma.libreria_damian.promedio(10,12,6,7,20)==11)
print("PROMEDIO OK")

assert(Damian_Coloma.libreria_damian.diferencia(100,5,4)==1)
assert(Damian_Coloma.libreria_damian.diferencia(100,29,14)==57)
assert(Damian_Coloma.libreria_damian.diferencia(890,59,478)==353)
assert(Damian_Coloma.libreria_damian.diferencia(150,17,78)==55)
assert(Damian_Coloma.libreria_damian.diferencia(100,5,6)==89)
print("DIFERENCIA OK")
